### ISSUE TITLE
[Question] How do I specify a gem if the name specified by require is different?

### ISSUE THREAD

**Issue by naitoh** [benchmark-driver/benchmark-driver#37]
I want to benchmark different versions of numo-narray.
How do I describe it?

Also, I would like to write in Ruby interface instead of YAML.
Is this possible?

# No Problem case

```
$ cat test.yaml 
contexts:
  - gems: { csv: 1.0.0}
  #- gems: { red-datasets : 0.0.4} #=> require 'datasets'
  #- gems: { numo-narray: 0.9.1.2} #=> require 'numo/narray'

loop_count: 2000000
prelude: |
  class Array
    alias_method :blank?, :empty?
  end
  array = []
benchmark:
  empty: array.empty?
  blank: array.blank?
```

```
$ benchmark-driver test.yaml
Calculating -------------------------------------
               empty    82.792M i/s -      2.000M times in 0.024157s (12.08ns/i, 27clocks/i)
               blank    46.137M i/s -      2.000M times in 0.043350s (21.67ns/i, 49clocks/i)

Comparison:
               empty:  82791583.2 i/s 
               blank:  46136503.8 i/s - 1.79x  slower
```

# Problem case

```
$ cat test.yaml 
contexts:
  #- gems: { csv: 1.0.0}
  #- gems: { red-datasets : 0.0.4} #=> require 'datasets'
  - gems: { numo-narray: 0.9.1.2} #=> require 'numo/narray'

loop_count: 2000000
prelude: |
  class Array
    alias_method :blank?, :empty?
  end
  array = []
benchmark:
  empty: array.empty?
  blank: array.blank?
```

```
$ benchmark-driver test.yaml
Calculating -------------------------------------
               emptyTraceback (most recent call last):
	2: from /tmp/benchmark_driver-20180708-14057-tpevk3.rb:2:in `<main>'
	1: from /home/naitoh/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/home/naitoh/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- numo-narray (LoadError)
Traceback (most recent call last):
	45: from /home/naitoh/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
	44: from /home/naitoh/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
	43: from /home/naitoh/.rvm/gems/ruby-2.5.1/bin/benchmark-driver:23:in `<main>'
	42: from /home/naitoh/.rvm/gems/ruby-2.5.1/bin/benchmark-driver:23:in `load'
	41: from /home/naitoh/.rvm/gems/ruby-2.5.1/gems/benchmark_driver-0.13.2/exe/benchmark-driver:111:in `<top (required)>'
```

```
$ irb
2.5.1 :001 > require 'numo/narray'
 => true 
```

# Environment

```
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
$ gem list benchmark_driver

*** LOCAL GEMS ***

benchmark_driver (0.13.2)
```

Best regards.

**Comment by k0kubun** [comment]
Yeah, I was too lazy to support this. Give me a sec to fix this issue...

**Comment by k0kubun** [comment]
Could you try this with benchmark_driver v0.13.3?

```yml
contexts:
  - gems: { csv: 1.0.0}
  - gems: { red-datasets : 0.0.4}
    require: false
    prelude: require 'datasets'
  - gems: { numo-narray: 0.9.1.2}
    require: false
    prelude: require 'numo/narray'

loop_count: 2000000
prelude: |
  class Array
    alias_method :blank?, :empty?
  end
  array = []
benchmark:
  empty: array.empty?
  blank: array.blank?
```
